# Start the Ollama server with an explicit model directory and make it survive reboots.
#
# Why this is needed:
#   The Ollama tray app in the Startup folder does NOT inherit custom environment
#   variables, so after a reboot the server may look in the wrong models folder and
#   every model request hangs.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\setup-ollama-autostart.ps1
#   powershell -ExecutionPolicy Bypass -File scripts\setup-ollama-autostart.ps1 `
#       -OllamaExe "D:\Ollama\ollama.exe" -ModelsDir "D:\Ollama\models"

param(
    [string]$OllamaExe  = (Join-Path $env:LOCALAPPDATA 'Programs\Ollama\ollama.exe'),
    [string]$ModelsDir  = '',
    [switch]$NoAutoStart
)

$ErrorActionPreference = 'Continue'

if (-not (Test-Path $OllamaExe)) {
    # Try the common per-machine location as a fallback
    $alt = Join-Path $env:ProgramFiles 'Ollama\ollama.exe'
    if (Test-Path $alt) { $OllamaExe = $alt }
    else { throw "ollama.exe not found. Pass -OllamaExe <path>." }
}

if ([string]::IsNullOrEmpty($ModelsDir)) {
    # Default: alongside the exe
    $ModelsDir = Join-Path (Split-Path -Parent $OllamaExe) 'models'
}

Write-Output ("ollama exe : {0}" -f $OllamaExe)
Write-Output ("models dir : {0}" -f $ModelsDir)
Write-Output ''

Write-Output '=== stop existing ollama processes ==='
Get-Process -ErrorAction SilentlyContinue | Where-Object { $_.ProcessName -match '^ollama' } | ForEach-Object {
    Write-Output ("stopping pid {0} {1}" -f $_.Id, $_.ProcessName)
    Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue
}
Start-Sleep -Seconds 3

Write-Output ''
Write-Output '=== start server with explicit env ==='
$env:OLLAMA_MODELS = $ModelsDir
$env:OLLAMA_CONTEXT_LENGTH = '16384'
$env:OLLAMA_HOST = '127.0.0.1:11434'
$env:OLLAMA_KEEP_ALIVE = '30m'
# Avoid the Intel iGPU being picked before the NVIDIA card on hybrid laptops
$env:OLLAMA_VULKAN = 'false'

$logDir = Join-Path $env:TEMP 'litreader'
New-Item -ItemType Directory -Path $logDir -Force | Out-Null
$log = Join-Path $logDir 'ollama-serve.log'

$p = Start-Process -FilePath $OllamaExe -ArgumentList 'serve' -PassThru -WindowStyle Hidden `
     -RedirectStandardOutput $log -RedirectStandardError "$log.err"
Write-Output ("started pid={0}" -f $p.Id)

for ($i = 1; $i -le 30; $i++) {
    Start-Sleep -Seconds 1
    try {
        $r = Invoke-RestMethod 'http://127.0.0.1:11434/api/version' -TimeoutSec 4 -ErrorAction Stop
        Write-Output ("API up after {0}s -> version {1}" -f $i, $r.version)
        break
    } catch { }
}

Write-Output ''
Write-Output '=== GPU check ==='
Get-Content $log, "$log.err" -ErrorAction SilentlyContinue |
    Select-String -Pattern 'inference compute' | Select-Object -Last 1 | ForEach-Object { $_.Line }

if ($NoAutoStart) {
    Write-Output ''
    Write-Output 'skipped autostart setup (-NoAutoStart)'
    exit 0
}

Write-Output ''
Write-Output '=== register autostart launcher ==='
$launcherDir = Join-Path $env:LOCALAPPDATA 'LitReader'
New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null
$launcher = Join-Path $launcherDir 'start-ollama.ps1'

$content = @"
# Auto-generated by LitReader setup. Starts Ollama with the correct model directory.
`$env:OLLAMA_MODELS = '$ModelsDir'
`$env:OLLAMA_CONTEXT_LENGTH = '16384'
`$env:OLLAMA_KEEP_ALIVE = '30m'
`$env:OLLAMA_VULKAN = 'false'
Start-Process -FilePath '$OllamaExe' -ArgumentList 'serve' -WindowStyle Hidden
"@
Set-Content -Path $launcher -Value $content -Encoding UTF8
Write-Output ("wrote launcher: {0}" -f $launcher)

$sh = New-Object -ComObject WScript.Shell
$startup = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'

# Remove the installer's Ollama shortcut, which does not set OLLAMA_MODELS
$oldLnk = Join-Path $startup 'Ollama.lnk'
if (Test-Path $oldLnk) {
    Remove-Item $oldLnk -Force
    Write-Output ("removed startup shortcut: {0}" -f $oldLnk)
}

$newLnk = Join-Path $startup 'Ollama Server.lnk'
$lnk = $sh.CreateShortcut($newLnk)
$lnk.TargetPath = 'powershell.exe'
$lnk.Arguments = '-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File "' + $launcher + '"'
$lnk.WorkingDirectory = $launcherDir
$lnk.Description = 'Start Ollama server with the correct model path'
$lnk.WindowStyle = 7
$lnk.Save()
Write-Output ("created startup shortcut: {0}" -f $newLnk)

Write-Output ''
Write-Output 'done'
